/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_string = 1,
  sym_date = 2,
  sym_decimal = 3,
  sym_integer = 4,
  anon_sym_TRUE = 5,
  anon_sym_FALSE = 6,
  sym_null = 7,
  anon_sym_COMMA = 8,
  sym_asterisk = 9,
  sym_keyword_select = 10,
  sym_identifier = 11,
  sym_source_file = 12,
  sym__statement = 13,
  sym__literal = 14,
  sym_boolean = 15,
  sym_select_statement = 16,
  sym__select_list = 17,
  sym_column_name = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym__select_list_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_string] = "string",
  [sym_date] = "date",
  [sym_decimal] = "decimal",
  [sym_integer] = "integer",
  [anon_sym_TRUE] = "TRUE",
  [anon_sym_FALSE] = "FALSE",
  [sym_null] = "null",
  [anon_sym_COMMA] = ",",
  [sym_asterisk] = "asterisk",
  [sym_keyword_select] = "keyword_select",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym_select_statement] = "select_statement",
  [sym__select_list] = "_select_list",
  [sym_column_name] = "column_name",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__select_list_repeat1] = "_select_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_string] = sym_string,
  [sym_date] = sym_date,
  [sym_decimal] = sym_decimal,
  [sym_integer] = sym_integer,
  [anon_sym_TRUE] = anon_sym_TRUE,
  [anon_sym_FALSE] = anon_sym_FALSE,
  [sym_null] = sym_null,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_asterisk] = sym_asterisk,
  [sym_keyword_select] = sym_keyword_select,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym_select_statement] = sym_select_statement,
  [sym__select_list] = sym__select_list,
  [sym_column_name] = sym_column_name,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__select_list_repeat1] = aux_sym__select_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TRUE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FALSE] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_asterisk] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_select] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_select_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__select_list] = {
    .visible = false,
    .named = true,
  },
  [sym_column_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__select_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 1,
        '*', 37,
        ',', 36,
        'F', 4,
        'N', 13,
        'T', 10,
        'S', 15,
        's', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 7:
      if (lookahead == 'L') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'L') ADVANCE(35);
      END_STATE();
    case 9:
      if (lookahead == 'L') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'R') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'S') ADVANCE(6);
      END_STATE();
    case 12:
      if (lookahead == 'U') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'U') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(38);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_date);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_decimal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_TRUE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_FALSE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_asterisk);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_keyword_select);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [sym_decimal] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_TRUE] = ACTIONS(1),
    [anon_sym_FALSE] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_asterisk] = ACTIONS(1),
    [sym_keyword_select] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(13),
    [sym__statement] = STATE(2),
    [sym__literal] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_select_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_string] = ACTIONS(5),
    [sym_date] = ACTIONS(5),
    [sym_decimal] = ACTIONS(5),
    [sym_integer] = ACTIONS(7),
    [anon_sym_TRUE] = ACTIONS(9),
    [anon_sym_FALSE] = ACTIONS(9),
    [sym_null] = ACTIONS(5),
    [sym_keyword_select] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_select_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_date] = ACTIONS(15),
    [sym_decimal] = ACTIONS(15),
    [sym_integer] = ACTIONS(17),
    [anon_sym_TRUE] = ACTIONS(9),
    [anon_sym_FALSE] = ACTIONS(9),
    [sym_null] = ACTIONS(15),
    [sym_keyword_select] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_select_statement] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_string] = ACTIONS(21),
    [sym_date] = ACTIONS(21),
    [sym_decimal] = ACTIONS(21),
    [sym_integer] = ACTIONS(24),
    [anon_sym_TRUE] = ACTIONS(27),
    [anon_sym_FALSE] = ACTIONS(27),
    [sym_null] = ACTIONS(21),
    [sym_keyword_select] = ACTIONS(30),
  },
  [STATE(4)] = {
    [aux_sym__select_list_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(33),
    [sym_string] = ACTIONS(33),
    [sym_date] = ACTIONS(33),
    [sym_decimal] = ACTIONS(33),
    [sym_integer] = ACTIONS(35),
    [anon_sym_TRUE] = ACTIONS(33),
    [anon_sym_FALSE] = ACTIONS(33),
    [sym_null] = ACTIONS(33),
    [anon_sym_COMMA] = ACTIONS(37),
    [sym_keyword_select] = ACTIONS(33),
  },
  [STATE(5)] = {
    [aux_sym__select_list_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_date] = ACTIONS(39),
    [sym_decimal] = ACTIONS(39),
    [sym_integer] = ACTIONS(41),
    [anon_sym_TRUE] = ACTIONS(39),
    [anon_sym_FALSE] = ACTIONS(39),
    [sym_null] = ACTIONS(39),
    [anon_sym_COMMA] = ACTIONS(37),
    [sym_keyword_select] = ACTIONS(39),
  },
  [STATE(6)] = {
    [aux_sym__select_list_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_string] = ACTIONS(43),
    [sym_date] = ACTIONS(43),
    [sym_decimal] = ACTIONS(43),
    [sym_integer] = ACTIONS(45),
    [anon_sym_TRUE] = ACTIONS(43),
    [anon_sym_FALSE] = ACTIONS(43),
    [sym_null] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(47),
    [sym_keyword_select] = ACTIONS(43),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(52), 1,
      sym_integer,
    ACTIONS(50), 9,
      ts_builtin_sym_end,
      sym_string,
      sym_date,
      sym_decimal,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_null,
      anon_sym_COMMA,
      sym_keyword_select,
  [15] = 2,
    ACTIONS(45), 1,
      sym_integer,
    ACTIONS(43), 9,
      ts_builtin_sym_end,
      sym_string,
      sym_date,
      sym_decimal,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_null,
      anon_sym_COMMA,
      sym_keyword_select,
  [30] = 2,
    ACTIONS(56), 1,
      sym_integer,
    ACTIONS(54), 8,
      ts_builtin_sym_end,
      sym_string,
      sym_date,
      sym_decimal,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_null,
      sym_keyword_select,
  [44] = 2,
    ACTIONS(60), 1,
      sym_integer,
    ACTIONS(58), 8,
      ts_builtin_sym_end,
      sym_string,
      sym_date,
      sym_decimal,
      anon_sym_TRUE,
      anon_sym_FALSE,
      sym_null,
      sym_keyword_select,
  [58] = 4,
    ACTIONS(62), 1,
      sym_asterisk,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(4), 1,
      sym_column_name,
    STATE(10), 1,
      sym__select_list,
  [71] = 2,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(8), 1,
      sym_column_name,
  [78] = 1,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 15,
  [SMALL_STATE(9)] = 30,
  [SMALL_STATE(10)] = 44,
  [SMALL_STATE(11)] = 58,
  [SMALL_STATE(12)] = 71,
  [SMALL_STATE(13)] = 78,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__select_list, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__select_list, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__select_list, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__select_list, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__select_list_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__select_list_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__select_list_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_name, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_name, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_select_statement, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_select_statement, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [66] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bql(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bql",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
